server:
  port: 9098

# http://localhost:9090/user-service-eureka-instance-name/user
eureka:
  instance:
    name: user-service-eureka-instance-name

# http://localhost:9090/user-service/user
spring:
  application:
    name: user-service
