server:
  port: 9099

# http://localhost:9090/book-service-eureka-instance-name/book
eureka:
  instance:
    name: book-service-eureka-instance-name

# http://localhost:9090/book-service/book
spring:
  application:
    name: book-service
